version: '3.8'

services:

  mongodb:
    container_name: mongodb
    image: mongo
    #command: bash -c "mongosh open5gs /docker-entrypoint-initdb.d/mongo-init.js"
    restart: unless-stopped
    environment:
      -MONGO_INITDB_DATABASE: open5gs
    expose:
      - "27017"
    volumes:
      - mongodb:/data/db
      - ./docs/assets/webui/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      open5gsnet:
        aliases:
          - mongodb

  open5gs-nrf:
    container_name: open5gsnrf
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/usr/local/bin/open5gs-nrfd;"
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
    cap_add:
      - NET_ADMIN
    networks:
      open5gsnet:
        aliases:
          - nrf.open5gs.org
  
  open5gs-scp:
    container_name: open5gsscp
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/usr/local/bin/open5gs-scpd;"
    depends_on:
      - open5gs-nrf
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
    cap_add:
      - NET_ADMIN
    networks:
      open5gsnet:
        aliases:
          - scp.open5gs.org

  open5gs-amf:
    container_name: open5gsamf
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/usr/local/bin/open5gs-amfd;"
    depends_on:
      - open5gs-nrf
      - open5gs-scp
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
    cap_add:
      - NET_ADMIN
    networks:
      open5gsnet:
        aliases:
          - amf.open5gs.org

  open5gs-smf:
    container_name: open5gssmf
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/usr/local/bin/open5gs-smfd;"
    depends_on:
      - open5gs-nrf
      - open5gs-scp
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
      - ./config/freeDiameter:/usr/local/etc/freeDiameter
    cap_add:
      - NET_ADMIN
    networks:
      open5gsnet:
        aliases:
          - smf.open5gs.org

  open5gs-ausf:
    container_name: open5gsausf
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/usr/local/bin/open5gs-ausfd;"
    depends_on:
      - open5gs-nrf
      - open5gs-scp
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
    cap_add:
      - NET_ADMIN
    networks:
      open5gsnet:
        aliases:
          - ausf.open5gs.org

  open5gs-udm:
    container_name: open5gsudm
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/usr/local/bin/open5gs-udmd;"
    depends_on:
      - open5gs-nrf
      - open5gs-scp
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
    cap_add:
      - NET_ADMIN
    networks:
      open5gsnet:
        aliases:
          - udm.open5gs.org

  open5gs-udr:
    container_name: open5gsudr
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/usr/local/bin/open5gs-udrd;"
    depends_on:
      - open5gs-nrf
      - open5gs-scp
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
    cap_add:
      - NET_ADMIN
    networks:
      open5gsnet:
        aliases:
          - udr.open5gs.org

  open5gs-nssf:
    container_name: open5gsnssf
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/usr/local/bin/open5gs-nssfd;"
    depends_on:
      - open5gs-nrf
      - open5gs-scp
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
    cap_add:
      - NET_ADMIN
    networks:
      open5gsnet:
        aliases:
          - nssf.open5gs.org

  open5gs-bsf:
    container_name: open5gsbsf
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/usr/local/bin/open5gs-bsfd;"
    depends_on:
      - open5gs-nrf
      - open5gs-scp
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
    cap_add:
      - NET_ADMIN
    networks:
      open5gsnet:
        aliases:
          - bsf.open5gs.org


  open5gs-pcf:
    container_name: open5gspcf
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/usr/local/bin/open5gs-pcfd;"
    depends_on:
      - open5gs-nrf
      - open5gs-scp
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
    cap_add:
      - NET_ADMIN
    networks:
      open5gsnet:
        aliases:
          - pcf.open5gs.org

  open5gs-upf:
    container_name: open5gsupf
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-build
    command: bash -c "/root/setup.sh; /usr/local/bin/open5gs-upfd;"
    depends_on:
      - open5gs-nrf
      - open5gs-scp
    volumes:
      - ./config/open5gs:/usr/local/etc/open5gs
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      open5gsnet:
        aliases:
          - upf.open5gs.org

  open5gs-webui:
    container_name: open5gs-webui
    image: ${USER}/open5gs-webui
    depends_on:
      - mongodb
    ports:
      - "9999:9999"
    environment:
      - DB_URI=mongodb://mongodb/open5gs
      - WAIT_HOSTS=mongodb:27017
    networks:
      open5gsnet:
        aliases:
          - webui.open5gs.org
  ueransim:
    container_name: ueransim
    image: free5gc/ueransim:latest
    command: ./nr-gnb -c ./config/open5gs-gnb.yaml
    volumes:
      - ./config/ueransim/open5gs-gnb.yaml:/ueransim/config/open5gs-gnb.yaml
      - ./config/ueransim/open5gs-ue.yaml:/ueransim/config/open5gs-ue.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      open5gsnet:
        aliases:
          - gnb.open5gs.org
    depends_on:
      - open5gs-amf
      - open5gs-upf
      - open5gs-smf


networks:
  open5gsnet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-open5gs

volumes:
  mongodb:
